version: "3"

services:
  db:
    image: mongo
    ports:
      - "27017:27017"
  db-client:
    restart: on-failure
    depends_on:
      - db
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_PORT=27017